import pygame

pygame.init()

# CONFIGURACIONES
FPS = 60
VENTANA_WIDTH = 800
VENTANA_HEIGHT = 800
VENTANA_MEDIDA = (VENTANA_WIDTH, VENTANA_HEIGHT)
VENTANA_CENTRO_WIDTH = VENTANA_WIDTH // 2
VENTANA_CENTRO_HEIGHT = VENTANA_HEIGHT // 2

# JUEGO
TIEMPO_INICIAL = 60
CANTIDAD_VIDAS = 5
PUNTUACION_ACIERTO = 100
PUNTUACION_ERROR = 50
MAX_ACIERTOS_SEGUIDOS = 3
VIDA_EXTRA_POR_ACIERTOS_SEGUIDOS = 1
TIEMPO_EXTRA_POR_ACIERTOS_SEGUIDOS = 20

# PATHS
FUENTE_PATH = "assets/kenney_future.ttf"
BOTON_VERDE_PATH = "assets/boton_verde.png"
BOTON_AZUL_PATH = "assets/boton_azul.png"
PREGUNTAS_CSV_PATH = "data/preguntas.csv"
MENU_CONTENEDOR_PADRE_PATH = "assets/menu_contenedor_padre.png"
MENU_CONTENEDOR_HIJO_PATH = "assets/menu_contenedor_hijo.png"
MENU_CONTENEDOR_PATH = "assets/menu_contenedor.png"
BACKGROUND_MENU_PRINCIPAL_PATH = "assets/background_menu_principal.jpg"
BACKGROUND_PARTIDA_PATH = "assets/background_partida.jpg"
CONTENEDOR_PREGUNTA_PATH = "assets/contenedor_pregunta.png"
CONTENEDOR_TIEMPO_PATH = "assets/contenedor_redondo_gris.png"
CONTENEDOR_VIDAS_PATH = "assets/contenedor_gris.png"
CONTENEDOR_PUNTUACION_PATH = "assets/contenedor_gris.png"
SONIDO_ACIERTO_PATH = "assets/sonido_acierto.mp3"
SONIDO_ERROR_PATH = "assets/sonido_error.mp3"

# PYGAME - IMAGENES
BACKGROUND_MENU_PRINCIPAL = pygame.image.load(BACKGROUND_MENU_PRINCIPAL_PATH)
BACKGROUND_PARTIDA = pygame.image.load(BACKGROUND_PARTIDA_PATH)
BOTON_VERDE = pygame.image.load(BOTON_VERDE_PATH)
BOTON_AZUL = pygame.image.load(BOTON_AZUL_PATH)
MENU_CONTENEDOR_PADRE = pygame.image.load(MENU_CONTENEDOR_PADRE_PATH)
MENU_CONTENEDOR_HIJO = pygame.image.load(MENU_CONTENEDOR_HIJO_PATH)
MENU_CONTENEDOR = pygame.image.load(MENU_CONTENEDOR_PATH)
CONTENEDOR_PREGUNTA = pygame.image.load(CONTENEDOR_PREGUNTA_PATH)
CONTENEDOR_TIEMPO = pygame.image.load(CONTENEDOR_TIEMPO_PATH)
CONTENEDOR_VIDAS = pygame.image.load(CONTENEDOR_VIDAS_PATH)
CONTENEDOR_PUNTUACION = pygame.image.load(CONTENEDOR_PUNTUACION_PATH)

# PYGAME - SONIDOS
SONIDO_ACIERTO = pygame.mixer.Sound(SONIDO_ACIERTO_PATH)
SONIDO_ERROR = pygame.mixer.Sound(SONIDO_ERROR_PATH)

# FUENTES
FUENTE_20 = pygame.font.Font(FUENTE_PATH, 20)
FUENTE_30 = pygame.font.Font(FUENTE_PATH, 30)
FUENTE_40 = pygame.font.Font(FUENTE_PATH, 40)
FUENTE_50 = pygame.font.Font(FUENTE_PATH, 50)
FUENTE_60 = pygame.font.Font(FUENTE_PATH, 60)

# VENTANAS
VENTANA_MENU_PRINCIPAL = 'MENU_PRINCIPAL'
VENTANA_SALIR = 'SALIR'
VENTANA_JUGAR = 'JUGAR'
VENTANA_FIN_PARTIDA = 'FIN_PARTIDA'

# MENU PRINCIPAL
MENU_PRINCIPAL_TITULO = "PREGUNTADOS"
MENU_PRINCIPAL_TITULO_COLOR = (64, 174, 120)
MENU_PRINCIPAL_TITULO_COLOR_SOMBRA = (45, 122, 84)

# COLORES
COLOR_BLANCO = (255,255,255)
COLOR_NEGRO = (0,0,0)
COLOR_VERDE = (0,255,0)
COLOR_ROJO = (255,0,0)
COLOR_AZUL = (0,0,255)
COLOR_VIOLETA = (134,23,219)