import pygame

pygame.init()

# CONFIGURACIONES
FPS = 60
VENTANA_WIDTH = 800
VENTANA_HEIGHT = 800
VENTANA_MEDIDA = (VENTANA_WIDTH, VENTANA_HEIGHT)

# PATHS
FUENTE_PATH = "assets/kenney_future.ttf"
BOTON_VERDE_PATH = "assets/boton_verde.png"
PREGUNTAS_CSV_PATH = "data/preguntas.csv"
MENU_CONTENEDOR_PADRE_PATH = "assets/menu_contenedor_padre.png"
MENU_CONTENEDOR_HIJO_PATH = "assets/menu_contenedor_hijo.png"
MENU_CONTENEDOR_PATH = "assets/menu_contenedor.png"
BACKGROUND_MENU_PRINCIPAL_PATH = "assets/background_menu_principal.jpg"

# PYGAME - IMAGENES
BACKGROUND_MENU_PRINCIPAL = pygame.image.load(BACKGROUND_MENU_PRINCIPAL_PATH)
BOTON_VERDE = pygame.image.load(BOTON_VERDE_PATH) 
MENU_CONTENEDOR_PADRE = pygame.image.load(MENU_CONTENEDOR_PADRE_PATH)
MENU_CONTENEDOR_HIJO = pygame.image.load(MENU_CONTENEDOR_HIJO_PATH)
MENU_CONTENEDOR = pygame.image.load(MENU_CONTENEDOR_PATH)

# FUENTES
FUENTE_30 = pygame.font.Font(FUENTE_PATH, 30)
FUENTE_40 = pygame.font.Font(FUENTE_PATH, 40)
FUENTE_50 = pygame.font.Font(FUENTE_PATH, 50)
FUENTE_60 = pygame.font.Font(FUENTE_PATH, 60)

# VENTANAS
VENTANA_MENU_PRINCIPAL = 'MENU_PRINCIPAL'
VENTANA_SALIR = 'SALIR'

# MENU PRINCIPAL
MENU_PRINCIPAL_TITULO = "PREGUNTADOS"
MENU_PRINCIPAL_TITULO_COLOR = (64, 174, 120)
MENU_PRINCIPAL_TITULO_COLOR_SOMBRA = (45, 122, 84)